services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diySign
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
      - ./package.json:/app/package.json
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-your_secure_password_here}
    restart: unless-stopped
